CarTime/Areas/User/Controllers/UserMainController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarTime.Areas.User.Controllers
{
    [Area("User")]
    public class UserMainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Controllers/MainController.cs
 using Microsoft.AspNetCore.Mvc;

namespace CarTime.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Controllers/ReturnCarController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Models;
using CarTime.Service;

namespace CarTime.Controllers
{
    public class ReturnCarController : Controller
    {
        private readonly AppDbContext _context;

        public ReturnCarController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ReturnOrder returnOrder = new ReturnOrder();
            return View(returnOrder);
        }
        [HttpPost]
        public IActionResult Index(ReturnOrder returnOrder)
        {
            if (ModelState.IsValid)
            {
                var order = _context.Orders.FirstOrDefault(o => o.Id == returnOrder.OrderId);
                if (order != null)
                {
                    returnOrder.DateAdding = DateTime.UtcNow;
                    returnOrder.Status = "created";
                    _context.ReturnOrders.Add(returnOrder);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(ReturnCarController.Thanks), nameof(ReturnCarController).CutController());
                }
            }
            return View(returnOrder);
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Views/ReturnCar/Index.cshtml
@model ReturnOrder

@{ 
    ViewBag.Title = "Заявка на возрат";
}

<div style="display:block; padding:100px 50px 50px 50px; width:30%">
    <form asp-controller="ReturnCar" asp-action="Index" method="post">
        <input type="hidden" asp-for="Id" />

        <div style="display: block;">
            <lable asp-for="Name">Имя</lable>
            <input asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="Surname">Фамилия</lable>
            <input asp-for="Surname" />
            <span asp-validation-for="Surname"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="Patronymic">Отчество</lable>
            <input asp-for="Patronymic" />
            <span asp-validation-for="Patronymic"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="Phone">Номер телефона</lable>
            <input asp-for="Phone" />
            <span asp-validation-for="Phone"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="Email">Почта</lable>
            <input asp-for="Email" />
            <span asp-validation-for="Email"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="OrderId">Номер заказа (в письме на почте)</lable>
            <input asp-for="OrderId" />
            <span asp-validation-for="OrderId"></span>
        </div>
        <div style="display: block;">
            <lable asp-for="Reason">Причина</lable>
            <input asp-for="Reason" />
            <span asp-validation-for="Reason"></span>
        </div>
        <div style="display: block;">
            <button type="submit">Подать заявку</button>
        </div>
    </form>    
    <form asp-controller="Main" asp-action="Index">
        <button type="submit" style="padding-top:30px;">Вернуться</button>
    </form>
</div>

CarTime/Views/ReturnCar/Thanks.cshtml
<div style="display:block; padding-top:100px; text-align:center">
    <h3>Заявка принята. Позже с вами свяжется менеджер.</h3>
    <button asp-controller="UserMain" asp-action="Index" type="submit">Вернуться на главную</button>
</div>