CarTime/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Service;

namespace CarTime.Controllers
{
    public class CarsController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly ShopCart _shopCart;

        public CarsController(DataManager dataManager, ShopCart shopCart)
        {
            _dataManager = dataManager;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            List<CarItem> Cars = _dataManager.CarItems.GetAvailableCars();
            return View(Cars);
        }

        public IActionResult CarDetails(Guid carId)
        {
            CarItem car = _dataManager.CarItems.GetCarById(carId);
            return View(car);
        }

        public IActionResult ToCart(Guid carId)
        {
            var item = _dataManager.CarItems.GetCarById(carId);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction(nameof(ShopCartController.Index), nameof(ShopCartController).CutController());
        }
    }
}

CarTime/Controllers/MainController.cs
 using Microsoft.AspNetCore.Mvc;

namespace CarTime.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Models;
using CarTime.Service;
using System;

namespace CarTime.Controllers 
{
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly DataManager _dataManager;
        private readonly ShopCart _shopCart;
        private readonly UserManager<UserData> _userManager;

        public OrderController(AppDbContext context, ShopCart shopCart, DataManager dataManager, UserManager<UserData> userManager)
        {
            _shopCart = shopCart;
            _context = context;
            _dataManager = dataManager;
            _userManager = userManager;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            _shopCart.ListShopItems = _shopCart.getShopItems();
            if (_shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары в корзине!");
                return RedirectToAction("Index", "ShopCart");
            }
            CreateOrderViewModel order = new CreateOrderViewModel();
            order.Price = _shopCart.cPrice(_shopCart.getShopItems());
            return View(order);
        }
        [HttpPost]
        public IActionResult Index(CreateOrderViewModel order)
        {
            _shopCart.ListShopItems = _shopCart.getShopItems();
            if (ModelState.IsValid)
            {
                Order newOrder = new Order();
                newOrder.Id = Guid.NewGuid();
                newOrder.Name = order.Name;
                newOrder.Surname = order.Surname;
                newOrder.Patronymic = order.Patronymic;
                newOrder.PhoneNumber = order.PhoneNumber;
                newOrder.Email = order.Email;
                newOrder.Address = order.Address;
                newOrder.Price = order.Price;
                newOrder.DateAdding = DateTime.UtcNow;
                newOrder.Status = "created";
                _dataManager.Orders.CreateOrder(newOrder);
                return RedirectToAction(nameof(MainController.Thanks), nameof(MainController).CutController());
            }

            return View(order);
        }
    }
}

CarTime/Views/Cars/CarDetails.cshtml
@model CarItem

@{
    ViewBag.Title = "Детали";
}

<div style="padding: 150px 50px 50px 50px; display: block;">
    <div style="display:inline-block;">
        <div style="width: 280px; height: 200px;">
            <img src="~/img/cars/@Model.TitleImagePath" width="100%" height="100%" />
        </div>
        <div style="display:block;">
            @Model.Title
            @Model.Price
        </div>
        <div style="display:block;">
            @Model.Text
        </div>
        <form asp-controller="Cars" asp-action="ToCart" asp-route-carId="@Model.Id">
            <button type="submit">Добавить в корзину</button>
        </form>
    </div>    
</div>

CarTime/Views/Cars/Index.cshtml
@model List<CarItem>
@{
    string strTitle = "Список доступных авто";
    ViewBag.Title = strTitle;
}

<div style="padding: 100px 50px 50px 50px;">
    <h2 align="center" padding-left="20px">@strTitle</h2>
    @foreach (CarItem car in Model)
    {
        <div style="display:inline-block; padding:50px 50px 50px 0">
            <div style="width:280px; height:200px;">
                <img src="~/img/cars/@car.TitleImagePath" width="100%" height="100%" />
            </div>
            <div>
                @car.Title<br />
                @car.SubTitle<br />
                <h5>@car.Price</h5>
            </div>
            <form asp-controller="Cars" asp-action="CarDetails" asp-route-carId="@car.Id">
                <button type="submit">Просмотреть детали</button>
            </form>
        </div>
    }
</div>

CarTime/Views/Cars/IndexCar.cshtml
@model List<CarItem>
@{
    string strTitle = "Список автомобилей";
    ViewBag.Title = strTitle;
}

<div style="padding-top: 100px;">
    <a asp-area="" asp-controller="Cars" asp-action="IndexCar" style="padding-right: 50px;">Арендовать авто</a>
    <a asp-area="" asp-controller="Cars" asp-action="IndexBike" >Арендовать велосипед</a>
</div>

<div style="padding-top: 20px;">
    <h2 align="center" padding-left="20px">@strTitle</h2>
    <div style="padding-left: 15px; padding-right: 15px;">
        @if (Model.Any())
        {
            @foreach (CarItem car in Model)
            {
                <a asp-area="" asp-controller="Order" asp-action="ShowDataCar" asp-route-id="@car.Id" style="display: inline-block">
                    <img src="~/img/cars/@car.TitleImagePath" width="90%" height="80%" />
                    <p>
                        @car.Title<br />
                        @car.SubTitle<br />
                        <h5>@car.Price</h5>
                    </p>
                </a>
            }
        }
        else
        {
            <p>Авто на данное время нет.</p>
            <a asp-area="" asp-controller="Main" asp-action="Index" ></a>
        }
    </div>
</div>