CarTime/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Service;

namespace CarTime.Controllers
{
    public class CarsController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly ShopCart _shopCart;

        public CarsController(DataManager dataManager, ShopCart shopCart)
        {
            _dataManager = dataManager;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            List<CarItem> Cars = _dataManager.CarItems.GetAvailableCars();
            return View(Cars);
        }

        public IActionResult CarDetails(Guid carId)
        {
            CarItem car = _dataManager.CarItems.GetCarById(carId);
            return View(car);
        }

        public IActionResult ToCart(Guid carId)
        {
            var item = _dataManager.CarItems.GetCarById(carId);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction(nameof(ShopCartController.Index), nameof(ShopCartController).CutController());
        }
    }
}

CarTime/Controllers/MainController.cs
 using Microsoft.AspNetCore.Mvc;

namespace CarTime.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Controllers/ReturnCarController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Models;
using CarTime.Service;

namespace CarTime.Controllers
{
    public class ReturnCarController : Controller
    {
        private readonly AppDbContext _context;

        public ReturnCarController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ReturnOrder returnOrder = new ReturnOrder();
            return View(returnOrder);
        }
        [HttpPost]
        public IActionResult Index(ReturnOrder returnOrder)
        {
            if (ModelState.IsValid)
            {
                var order = _context.Orders.FirstOrDefault(o => o.Id == returnOrder.OrderId);
                if (order != null)
                {
                    returnOrder.DateAdding = DateTime.UtcNow;
                    returnOrder.Status = "created";
                    _context.ReturnOrders.Add(returnOrder);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(ReturnCarController.Thanks), nameof(ReturnCarController).CutController());
                }
            }
            return View(returnOrder);
        }

        public IActionResult Thanks()
        {
            return View();
        }
    }
}

CarTime/Views/Main/Index.cshtml
<section id="banner">

    <div class="inner">
        <h4>Добро пожаловть на CarTime</h4>
        <p>
            Здесь вы сможете найти машину мечты.
        </p>
        <div style="display:inline-block; padding-top:30px;">
            <form asp-controller="Cars" asp-action="Index">
                <button type="submit" style="padding-right:20px;">Заказать авто</button>
            </form>
        </div>
        <div style="display:inline-block;">
            <form asp-controller="ReturnCar" asp-action="Index">
                <button type="submit">Вернуть авто</button>
            </form>
        </div>
    </div>

</section>

CarTime/Views/Main/Thanks.cshtml
<div style="display: block; padding: 100px 0 0 0; text-align:center">
    <h3>Заказ оформлен. Позже с вами свяжется менеджер, для уточнения деталей.</h3>
    
    <div style="display: block; padding-top: 75px;">
        <form asp-controller="Main" asp-action="Index">
            <button type="submit">На главную</button>
        </form>
    </div>
</div>