CarTime/Areas/User/Controllers/UserCarsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Service;

namespace CarTime.Areas.User.Controllers
{
    [Area("User")]
    public class UserCarsController : Controller
    {
        private readonly DataManager _dataManager;
        private readonly ShopCart _shopCart;

        public UserCarsController(DataManager dataManager, ShopCart shopCart)
        {
            _dataManager = dataManager;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            List<CarItem> Cars = _dataManager.CarItems.GetAvailableCars();
            return View(Cars);
        }

        public IActionResult CarDetails(Guid carId)
        {
            CarItem car = _dataManager.CarItems.GetCarById(carId);
            return View(car);
        }

        public IActionResult ToCart(Guid carId)
        {
            var item = _dataManager.CarItems.GetCarById(carId);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index", "UserShopCart");
        }
    }
}

CarTime/Areas/User/Controllers/UserOrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Models;
using CarTime.Service;
using System;
using System.Linq;

namespace CarTime.Areas.User.Controllers
{
    [Area("User")]
    public class UserOrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly DataManager _dataManager;
        private readonly ShopCart _shopCart;
        private readonly UserManager<UserData> _userManager;

        public UserOrderController(AppDbContext context, ShopCart shopCart, DataManager dataManager, UserManager<UserData> userManager)
        {
            _shopCart = shopCart;
            _context = context;
            _dataManager = dataManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            _shopCart.ListShopItems = _shopCart.getShopItems();
            if (_shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары в корзине!");
                return RedirectToAction("Index", "ShopCart");
            }

            CreateOrderViewModel order = new CreateOrderViewModel();

            order.Price = _shopCart.cPrice(_shopCart.getShopItems());

            string userId = HttpContext.Session.GetString("UserId");

            UserData user = new UserData();
            user = _context.UserData.FirstOrDefault(u => u.Id == userId);

            order.UserDataId = new Guid(user.Id);
            order.Name = user.Name;
            order.Surname = user.Surname;
            order.Patronymic = user.Patronymic;
            order.PhoneNumber = user.PhoneNumber;
            order.Email = user.Email;

            return View(order);
        }
        [HttpPost]
        public IActionResult Index(CreateOrderViewModel order)
        {
            _shopCart.ListShopItems = _shopCart.getShopItems();
            if (ModelState.IsValid)
            {
                Order newOrder = new Order();

                newOrder.Id = Guid.NewGuid();
                string userId = HttpContext.Session.GetString("UserId");
                newOrder.UserDataId = new Guid(userId);
                newOrder.Name = order.Name;
                newOrder.Surname = order.Surname;
                newOrder.Patronymic = order.Patronymic;
                newOrder.PhoneNumber = order.PhoneNumber;
                newOrder.Email = order.Email;
                newOrder.Address = order.Address;
                newOrder.Price = order.Price;
                newOrder.DateAdding = DateTime.UtcNow;
                newOrder.Status = "created";

                _dataManager.Orders.CreateOrder(newOrder);

                return RedirectToAction("Thanks", "UserMain");
            }
            return View(order);
        }
    }
}

CarTime/Areas/User/Controllers/UserShopCartController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CarTime.Domain;
using CarTime.Domain.Entities;
using CarTime.Models;

namespace CarTime.Areas.User.Controllers
{
    [Area("User")]
    public class UserShopCartController : Controller
    {
        private readonly ShopCart _shopCart;
        private readonly AppDbContext _context;

        public UserShopCartController(ShopCart shopCart, AppDbContext context)
        {
            _shopCart = shopCart;
            _context = context;
        }

        public IActionResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.ListShopItems = items;
      
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart,
                Price = _shopCart.cPrice(items)
            };
            
            return View(obj);
        }

        [HttpGet]
        public IActionResult DeleteFromCart(Guid shopCartItemId)
        {
            var item = _context.ShopCartItems.FirstOrDefault(i => i.Id == shopCartItemId);
            _shopCart.DeleteFromCart(item);
            return RedirectToAction("Index", "UserShopCart");
        }
    }
}

CarTime/Areas/User/Views/UserShopCart/Index.cshtml
@model ShopCartViewModel

    <div style="padding: 150px 50px 50px 50px; display: block">
        @foreach (var cart in Model.shopCart.ListShopItems)
        {
            <div style="display:inline-block; padding:0 0 20px 50px;">
                <div style="width:280px; height:200px;">
                    <img src="~/img/cars/@cart.CarItem.TitleImagePath" width="100%" height="100%" />
                </div>
                <div style="display:block;">
                    @cart.CarItem.Title
                    @cart.CarItem.Price
                </div>
                <div>
                    <a asp-area="User" asp-controller="UserShopCart" asp-action="DeleteFromCart" asp-route-shopCartItemId="@cart.Id" method="get">Удалить из корзины</a>
                </div>
            </div>
        }
    </div>
    <div style="padding: 0 50px 20px 50px;">
        @Model.Price
        <div style="display:inline-block; padding-right:10px;">
            <form asp-area="User" asp-controller="UserOrder" asp-action="Index">
                <button type="submit">Оплатить</button>
            </form>
        </div>
        <div style="display:inline-block;">
            <form asp-area="User" asp-controller="UserCars" asp-action="Index">
                <button type="submit">К списку авто</button>
            </form>
        </div>
    </div>